# YAML linting configuration for yamllint
# ==============================================================================

extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  document-start: disable  # Don't require --- at start

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false  # Allow yes/no in keys like "restart: unless-stopped"

  # Allow duplicate keys in docker-compose (for environment vars)
  key-duplicates:
    forbid-duplicated-merge-keys: true
